{
 "title": "Containers",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,container_name)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{job=\"integrations/docker\"})"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{job=\"$job\"}[5m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=~\"$name\"}[5m]) * 100",
     "legendFormat": "{{container_name}}({{container_id}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{container_name=~\"$name\"}[5m]) * 100",
     "legendFormat": "{{container_name}}({{container_id}})"
    }
   ]
  },
  {
   "title": "Network IO RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (container_name,container_id) (irate(container_network_receive_bytes_total{container_name=~\"$name\"}[5m]))",
     "legendFormat": "RX: {{container_name}}({{container_id}})"
    },
    {
     "expr": "sum by (container_name,container_id) (irate(container_network_transmit_bytes_total{container_name=~\"$name\"}[5m]))",
     "legendFormat": "TX: {{container_name}}({{container_id}})"
    }
   ]
  },
  {
   "title": "Disk IO R/W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (container_name,container_id) (irate(container_fs_reads_bytes_total{container_name=~\"$name\"}[5m]))",
     "legendFormat": "R: {{container_name}}({{container_id}})"
    },
    {
     "expr": "sum by (container_name,container_id) (irate(container_fs_writes_bytes_total{container_name=~\"$name\"}[5m]))",
     "legendFormat": "W: {{container_name}}({{container_id}})"
    }
   ]
  },
  { "title": "LOGS: $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "name" },
  {
   "title": "$name",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{container_name=\"$name\"} |= ``",
     "legendFormat": "{{container_name}}({{container_id}})"
    }
   ]
  }
 ]
}