version: "3.9"
networks:
  default:
    name: ghilbut
    external: true
services:
  pyroscope:
    container_name: pyroscope
    image: grafana/pyroscope:1.4.0
    command: [ "-config.expand-env=true", "-config.file=/etc/pyroscope/config.yaml" ]
    environment:
      MINIO_ACCESS_KEY: ${GF_PYROSCOPE_MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${GF_PYROSCOPE_MINIO_SECRET_KEY}
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4040/ready || exit 1" ]
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 1s
    ports:
      - "127.0.0.1:4040:4040"
    read_only: true
    restart: always
    volumes:
      - ./pyroscope.yaml:/etc/pyroscope/config.yaml:ro
      - ../.data/grafana-pyroscope:/var/lib/pyroscope
    working_dir: /var/lib/pyroscope
