version: "3.9"
networks:
  default:
    name: ghilbut
    external: true
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:10.3.3
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_DATABASE_PASSWORD: 'postgrespw'
      GF_FEATURE_TOGGLES_ENABLE: 'flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor'
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:3000/healthz || exit 1 || exit 1" ]
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 1s
    ports:
      - "127.0.0.1:3000:3000"
    read_only: true
    restart: always
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - ./definitions:/var/lib/grafana/dashboards:ro
      - ./provisioning:/etc/grafana/provisioning:ro
      - ../.data/grafana:/var/lib/grafana
