version: "3.9"
networks:
  default:
    name: ghilbut
    external: true
services:
  loki:
    container_name: loki
    image: grafana/loki:2.9.4
    command: [ "-config.expand-env=true", "-config.file=/etc/loki/config.yaml" ]
    environment:
      MINIO_ACCESS_KEY: ${GF_LOKI_MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${GF_LOKI_MINIO_SECRET_KEY}
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 1s
    ports:
      - "127.0.0.1:3100:3100"
      - "127.0.0.1:7946:7946"
      - "127.0.0.1:9095:9095"
    read_only: true
    restart: always
    volumes:
      - ./loki.yaml:/etc/loki/config.yaml:ro
      - ../.data/grafana-loki:/loki
